"""Pydantic data models for GrimmLink Adapter."""

from grimmlink_adapter.models.grimmlink import (
    GrimmlinkAnnotationPayload,
    GrimmlinkAuthResponse,
    GrimmlinkBookmarkPayload,
    GrimmlinkBookSummary,
    GrimmlinkCapabilitiesResponse,
    GrimmlinkItemResult,
    GrimmlinkLocationPayload,
    GrimmlinkMetadataBatchResponse,
    GrimmlinkMetadataPullItem,
    GrimmlinkMetadataPullResponse,
    GrimmlinkMetadataSyncRequest,
    GrimmlinkMetadataSyncResponse,
    GrimmlinkRatingPayload,
    GrimmlinkReadingSessionBatchRequest,
    GrimmlinkReadingSessionBatchResponse,
    GrimmlinkReadingSessionItemRequest,
    GrimmlinkReadStatusRequest,
    GrimmlinkShelfRemovalResponse,
    GrimmlinkShelfSummary,
    KoreaderProgressPayload,
)
from grimmlink_adapter.models.internal import (
    BookHashEntry,
    CachedToken,
    NormalizedProgress,
    OutboxAction,
)
from grimmlink_adapter.models.official import (
    OfficialBookDTO,
    OfficialBookFileDTO,
    OfficialBulkShelfAssignRequest,
    OfficialLoginRequest,
    OfficialLoginResponse,
    OfficialMagicShelfDTO,
    OfficialReadingSessionDTO,
    OfficialShelfDTO,
)

__all__ = [
    "GrimmlinkAnnotationPayload",
    "GrimmlinkAuthResponse",
    "GrimmlinkBookmarkPayload",
    "GrimmlinkBookSummary",
    "GrimmlinkCapabilitiesResponse",
    "GrimmlinkItemResult",
    "GrimmlinkLocationPayload",
    "GrimmlinkMetadataBatchResponse",
    "GrimmlinkMetadataPullItem",
    "GrimmlinkMetadataPullResponse",
    "GrimmlinkMetadataSyncRequest",
    "GrimmlinkMetadataSyncResponse",
    "GrimmlinkRatingPayload",
    "GrimmlinkReadingSessionBatchRequest",
    "GrimmlinkReadingSessionBatchResponse",
    "GrimmlinkReadingSessionItemRequest",
    "GrimmlinkReadStatusRequest",
    "GrimmlinkShelfRemovalResponse",
    "GrimmlinkShelfSummary",
    "KoreaderProgressPayload",
    "BookHashEntry",
    "CachedToken",
    "NormalizedProgress",
    "OutboxAction",
    "OfficialBookDTO",
    "OfficialBookFileDTO",
    "OfficialBulkShelfAssignRequest",
    "OfficialLoginRequest",
    "OfficialLoginResponse",
    "OfficialMagicShelfDTO",
    "OfficialReadingSessionDTO",
    "OfficialShelfDTO",
]
